// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Persistencia.Models;

public partial class BienesConstatado
{
    public int Id { get; set; }

    public int CodigoEsbay { get; set; }

    public string CodigoOlimpo { get; set; }

    public string Descripcion { get; set; }

    public string Serie { get; set; }

    public int? IdUsuario { get; set; }

    public bool? Constatado { get; set; }

    public string Modelo { get; set; }

    public string Marca { get; set; }

    public string Custodio { get; set; }

    public DateTime? FechaIngreso { get; set; }

    public int IdCampus { get; set; }

    public DateTime? FechaConstatacion { get; set; }

    public virtual Bien CodigoEsbayNavigation { get; set; }
}