// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Persistencia.Models;

public partial class BienBaja
{
    public int Id { get; set; }

    public string Observacion { get; set; }

    public int CodigoEsbay { get; set; }

    public string TipoEstadoBien { get; set; }

    public string RolAudd { get; set; }

    public DateTime? FechaTransaccion { get; set; }

    public virtual Bien CodigoEsbayNavigation { get; set; }
}