// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Persistencia.Models;

public partial class Bien
{
    public int CodigoEsbay { get; set; }

    public string CodigoOlimpo { get; set; }

    public string Descripcion { get; set; }

    public string Serie { get; set; }

    public string Modelo { get; set; }

    public string Marca { get; set; }

    public string Custodio { get; set; }

    public DateTime FechaIngreso { get; set; }

    public int? IdDependencia { get; set; }

    public DateTime? FechaConstatacion { get; set; }

    public bool Constatado { get; set; }

    public int? IdTipoMantenimiento { get; set; }

    public DateTime? FechaTransaccion { get; set; }

    public string Observaciones { get; set; }

    public int? IdCampus { get; set; }

    public virtual ICollection<BienBaja> BienBajas { get; set; } = new List<BienBaja>();

    public virtual ICollection<BienesConstatado> BienesConstatados { get; set; } = new List<BienesConstatado>();

    public virtual Campus IdCampusNavigation { get; set; }

    public virtual Dependencium IdDependenciaNavigation { get; set; }

    public virtual TipoMantenimiento IdTipoMantenimientoNavigation { get; set; }

    public virtual ICollection<Mantenimiento> Mantenimientos { get; set; } = new List<Mantenimiento>();
}