// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Persistencia.Models;

public partial class Campus
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string IdUsuarioAudd { get; set; }

    public string RolAudd { get; set; }

    public string DireccionIpAudd { get; set; }

    public string SistemaAudd { get; set; }

    public DateTime FechaTransaccion { get; set; }

    public virtual ICollection<Bien> Biens { get; set; } = new List<Bien>();
}