// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Persistencia.Models;

public partial class Mantenimiento
{
    public int Id { get; set; }

    public int CodigoEsbay { get; set; }

    public string MotivoMantenimiento { get; set; }

    public string AccionesRealizadas { get; set; }

    public string NombreTecnico { get; set; }

    public string Resultado { get; set; }

    public int? IdTipoEstadoBien { get; set; }

    public virtual Bien CodigoEsbayNavigation { get; set; }

    public virtual TipoEstadoBien IdTipoEstadoBienNavigation { get; set; }
}