// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Persistencia.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public int? NumCelular { get; set; }

    public string Correo { get; set; }

    public string Clave { get; set; }
}